url: https://fardane.com

title: "الدكتور فردان"
tagline: "باحث في تاريخ المياه - جامعة القاضي عياض، مراكش"
description: >-
    موقع الدكتور فردان المتخصص في تاريخ المياه والدراسات التاريخية 
        في المغرب وشمال أفريقيا. أستاذ بجامعة القاضي عياض في مراكش.

timezone: "Africa/Casablanca"
lang: "ar"
direction: "rtl"

highlighter: none

plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
    - faraday-retry

exclude:
    - "*.config.js"
    - "package*.json"
    - assets
    - _data/manifest.json
    - node_modules
    - CNAME
    - "Gemfile*"
    - ".idea"

# Default Front Matter
defaults:
    -   scope:
            path: ""
            type: "pages"
        values:
            layout: "default"
            title:
            description:
            lang: "ar"
            direction: "rtl"
